# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        name: github-pages
        path: dist/
        retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        # Name of the artifact to deploy
        artifact_name:  github-pages
                
                  
